### ISSUE TITLE
無法裁切原始大小

### ISSUE THREAD

**Issue by k52252467** [huchang47/AetherConverTools#1]
File "C:\Users\User\Desktop\AetherConverTools-workflow\bin\Stage1.py", line 272, in <module>
    f.write("选的是我")
UnicodeEncodeError: 'cp950' codec can't encode character '\u9009' in position 0: illegal multibyte sequence

C:\Users\User\Desktop\AetherConverTools-workflow\bin>pause

無法裁切原始大小

**Comment by huchang47** [comment]
你不是简体中文语言环境吧？可能导致生成的坐标文件出现了编码问题。
我是没想到会有其他语言的人使用这个小众的工具。

在我更新修复前，临时的解决方法是：手动将bin目录下的【原始坐标.txt】文件，转换成utf-8格式。注意最后一行的字，不能是乱码。

**Comment by k52252467** [comment]
> 你不是簡體中文語言環境吧？可能導致生成的坐標文件出現編碼問題。 我很意外會有其他語言的人使用這個小工具。
> 
> 在我更新修復前，臨時的解決方法是：手動將bin目錄下的【原始坐標.txt】文件，轉換成utf-8格式。注意最後一行的字，不能是亂碼。

是的
我不是簡中
我會試試的
謝謝

**Comment by huchang47** [comment]
理论上已于0.94修正
