### ISSUE TITLE
裁切分辨率

### ISSUE THREAD

**Issue by YHD233** [huchang47/AetherConverTools#2]
裁切分辨率可以指定为8的倍数吗，我看webui那边有人说用那些不是8的倍数的分辨率，跑图的时候速度会变慢而且显存占用大很多
[https://github.com/vladmandic/automatic/discussions/1448](url)

**Comment by huchang47** [comment]
可以，这正是下一个工作目标。
不仅仅是跑图慢，而是会被sd强制变成8的倍数。这样生成之后的图放回去就会有一些偏差了。

**Comment by huchang47** [comment]
Fixed.
