### ISSUE TITLE
協助使用EBS

### ISSUE THREAD

**Issue by k52252467** [huchang47/AetherConverTools#5]
由於每秒15幀的工作量太大了，
我使用EBS的關鍵幀來節約幀數，
當我使用圖生圖生成完後，
我需要將圖片合併回原始圖片，
我的圖片尺寸是最小SIZE，
所以圖片尺寸大小皆不相同，
當我合併時，
有些圖片明顯比例不正確，

它似乎不是比對名字!?
而是根據順序合併!?

**Comment by huchang47** [comment]
整合EBS的工作正在进行中，要不了多久的时间，就可以在工作流中无缝使用EBS技术了。

是的，确实不比对名字，只是按照序列来进行操作。
原因有2：
1. 速度，序列比匹配名字快百倍，视频普遍几千帧的情况下，速度必须是一个需要考量的因素。
2. 减少错误发生，虽然工作流生成的阶段性文件都保证了名称的统一，但不能保证不使用工作流的步骤也如此，比如不少工具会增加_map、_mask等后缀，导致引发额外的不必要问题。
