### ISSUE TITLE
进行05图生图报错, 用的秋叶包, 秋叶包里没有报错信息

### ISSUE THREAD

**Issue by one0oneChen** [huchang47/AetherConverTools#8]
是否启用ADetailer进行脸部修复（请确保你正确安装了该插件，否则可能出错）？
1. 是
2. 否
请输入选择编号：2
ControlNet的模型对应字典:control_dict {'canny': 'control_v11p_sd15_canny_fp16 [b18e0966]', 'invert (from white bg & black line)': 'control_v11p_sd15_scribble_fp16 [4e6af23e]', 'depth_leres': 'control_v11f1p_sd15_depth_fp16 [4b72d323]', 'depth_leres++': 'control_v11f1p_sd15_depth_fp16 [4b72d323]', 'depth_midas': 'control_v11f1p_sd15_depth_fp16 [4b72d323]', 'depth_zoe': 'control_v11f1p_sd15_depth_fp16 [4b72d323]', 'normal_bae': 'control_v11p_sd15_normalbae_fp16 [592a19d8]', 'normal_midas': 'control_v11p_sd15_normalbae_fp16 [592a19d8]', 'dw_openpose_full': 'control_v11p_sd15_openpose_fp16 [73c2b67d]', 'openpose': 'control_v11p_sd15_openpose_fp16 [73c2b67d]', 'openpose_face': 'control_v11p_sd15_openpose_fp16 [73c2b67d]', 'openpose_faceonly': 'control_v11p_sd15_openpose_fp16 [73c2b67d]', 'openpose_full': 'control_v11p_sd15_openpose_fp16 [73c2b67d]', 'openpose_hand': 'control_v11p_sd15_openpose_fp16 [73c2b67d]', 'mlsd': 'control_v11p_sd15_mlsd_fp16 [77b5ad24]', 'lineart_anime': 'control_v11p_sd15_lineart_fp16 [5c23b17d]', 'lineart_anime_denoise': 'control_v11p_sd15_lineart_fp16 [5c23b17d]', 'lineart_coarse': 'control_v11p_sd15_lineart_fp16 [5c23b17d]', 'lineart_realistic': 'control_v11p_sd15_lineart_fp16 [5c23b17d]', 'lineart_standard (from white bg & black line)': 'control_v11p_sd15_lineart_fp16 [5c23b17d]', 'softedge_hed': 'control_v11p_sd15_softedge_fp16 [f616a34f]', 'softedge_hedsafe': 'control_v11p_sd15_softedge_fp16 [f616a34f]', 'softedge_pidinet': 'control_v11p_sd15_softedge_fp16 [f616a34f]', 'softedge_pidisafe': 'control_v11p_sd15_softedge_fp16 [f616a34f]', 'scribble_hed': 'control_v11p_sd15_scribble_fp16 [4e6af23e]', 'scribble_pidinet': 'control_v11p_sd15_scribble_fp16 [4e6af23e]', 'scribble_xdog': 'control_v11p_sd15_scribble_fp16 [4e6af23e]', 'seg_ofade20k': 'control_v11p_sd15_seg_fp16 [ab613144]', 'seg_ofcoco': 'control_v11p_sd15_seg_fp16 [ab613144]', 'seg_ufade20k': 'control_v11p_sd15_seg_fp16 [ab613144]', 'shuffle': 'control_v11e_sd15_shuffle_fp16 [04a71f87]', 'tile_colorfix': 'control_v11f1e_sd15_tile_fp16 [3b860298]', 'tile_colorfix+sharp': 'control_v11f1e_sd15_tile_fp16 [3b860298]', 'tile_resample': 'control_v11f1e_sd15_tile_fp16 [3b860298]', 'inpaint_global_harmonious': 'control_v11p_sd15_inpaint_fp16 [be8bc0ed]', 'inpaint_only': 'control_v11p_sd15_inpaint_fp16 [be8bc0ed]', 'inpaint_only+lama': 'control_v11p_sd15_inpaint_fp16 [be8bc0ed]', 'reference_adain': 'None', 'reference_adain+attn': 'None', 'reference_only': 'None', 't2ia_color_grid': 'None', 't2ia_sketch_pidi': 'None', 't2ia_style_clipvision': 'None'}

是否使用以太内门心法？(测试中功能)
1. 是
2. 否
请输入你的选择：2
00001.png开始生成！生成尺寸为512x792像素
错误：处理图生图时出现异常，请查看SD控制台报错信息。
'images'

如下:
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
current transparent-background 1.2.4

Launching Web UI with arguments: --theme dark --xformers --api --autolaunch
[AddNet] Updating model hashes...
[AddNet] Updating model hashes...
2023-09-02 07:57:27,210 - ControlNet - INFO - ControlNet v1.1.313
ControlNet preprocessor location: E:\AIGC\秋叶整合包\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\annotator\downloads
2023-09-02 07:57:27,532 - ControlNet - INFO - ControlNet v1.1.313
Loading weights [32c4949218] from E:\AIGC\秋叶整合包\sd-webui-aki-v4.2\models\Stable-diffusion\V08_V08.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 42.4s (launcher: 14.8s, import torch: 8.3s, import gradio: 3.2s, setup paths: 3.0s, other imports: 2.4s, setup codeformer: 0.2s, list SD models: 0.1s, load scripts: 7.0s, create ui: 2.4s, gradio launch: 0.6s, add APIs: 0.2s).
Creating model from config: E:\AIGC\秋叶整合包\sd-webui-aki-v4.2\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
Model loaded in 16.5s (load weights from disk: 3.8s, create model: 1.0s, apply weights to model: 2.4s, apply half(): 1.5s, move model to device: 7.3s, calculate empty prompt: 0.3s).
2023-09-02 07:58:35,785 - ControlNet - INFO - Loading model: control_v11p_sd15_softedge_fp16 [f616a34f]
2023-09-02 07:58:35,851 - ControlNet - INFO - Loaded state_dict from [E:\AIGC\秋叶整合包\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\models\control_v11p_sd15_softedge_fp16.safetensors]
2023-09-02 07:58:35,852 - ControlNet - INFO - Loading config: E:\AIGC\秋叶整合包\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\models\control_v11p_sd15_softedge.yaml
2023-09-02 07:58:42,162 - ControlNet - INFO - ControlNet model control_v11p_sd15_softedge_fp16 [f616a34f] loaded.
2023-09-02 07:58:42,235 - ControlNet - INFO - Loading preprocessor: pidinet
2023-09-02 07:58:42,235 - ControlNet - INFO - preprocessor resolution = 584
2023-09-02 07:58:42,319 - ControlNet - INFO - Loaded state_dict from [E:\AIGC\秋叶整合包\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\annotator\downloads\pidinet\table5_pidinet.pth]

**Comment by manling6** [comment]
俺也一样

**Comment by one0oneChen** [comment]
我这边无法使用bat文件进行图生图, 用isnet插件可以, 注意图生图那个框里需要随便放一张视频的参考图否则报错 AttributeError: 'NoneType' object has no attribute 'convert'

**Comment by manling6** [comment]
> 我这边无法使用bat文件进行图生图, 用isnet插件可以, 注意图生图那个框里需要随便放一张视频的参考图否则报错 AttributeError: 'NoneType' object has no attribute 'convert'

我试了，用喵手的整合包就没问题

**Comment by huchang47** [comment]
I'm not sure if it's the Chinese path, but I think it's a good idea to try tweaking that part.

**Comment by one0oneChen** [comment]
> I'm not sure if it's the Chinese path, but I think it's a good idea to try tweaking that part.

thanks for your reply, I have tested Ascii path, It has not change, The problem still exists

**Comment by one0oneChen** [comment]
> > 我这边无法使用bat文件进行图生图, 用isnet插件可以, 注意图生图那个框里需要随便放一张视频的参考图否则报错 AttributeError: 'NoneType' object has no attribute 'convert'
> 
> 我试了，用喵手的整合包就没问题

那就是秋叶整合包的环境问题, 现在比较麻烦由于不是直接用cmd运行, 看不到最原始的报错, 一般来说如果可以调用sd-webui的api, 那cmd那边肯定有报错信息

**Comment by huchang47** [comment]
这个问题已经解决了。是由于没有安装ADetailer脸部修复插件导致的（无论是否使用）。
解决方案是更新到最新版，已做了这部分的容错。或者安装ADetailer。
